# Generated by Django 6.1 on 2026-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pokedex_id', models.IntegerField(unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('base_experience', models.IntegerField()),
                ('types', models.JSONField()),
                ('abilities', models.JSONField()),
                ('stats', models.JSONField()),
                ('sprite', models.URLField()),
            ],
        ),
    ]
