# Generated by Django 6.1 on 2026-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0002_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='total_stats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
