# Generated by Django 6.1 on 2026-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0003_species_total_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('move_id', models.IntegerField(unique=True)),
                ('power', models.IntegerField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('effect_chance', models.IntegerField(null=True)),
                ('pp', models.IntegerField()),
                ('meta', models.JSONField()),
                ('stat_changes', models.JSONField(null=True)),
                ('priority', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('damage_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
