# Generated by Django 6.1 on 2026-09-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedata', '0004_moves_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moves',
            name='meta',
            field=models.JSONField(null=True),
        ),
    ]
